name: postsubmit

on:
  push:
    branches: [main, cloudflare]

permissions:
  contents: read
  deployments: write
  packages: write
  id-token: write 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Build assets
        run: pnpm install && pnpm build
        env:
          VITE_COMMIT_SHA: ${{ github.sha }}
      - name: Upload assets
        uses: actions/upload-artifact@v4
        with:
          name: assets
          path: apps/web/dist
          retention-days: 7
  # release-docker:
  #   runs-on: ubuntu-latest
  #   needs: [build]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Download assets
  #       uses: actions/download-artifact@v4
  #       with:
  #         name: assets
  #         path: apps/web/dist
  #     - name: Install Cosign
  #       uses: sigstore/cosign-installer@v3.5.0
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Log in to GHCR
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Tag image
  #       uses: docker/metadata-action@v5
  #       id: meta
  #       with:
  #         images: ghcr.io/${{ github.repository }}
  #         tags: |
  #           type=raw,value=${{ github.sha }}
  #           type=raw,value=latest
  #     - name: Build and push image
  #       uses: docker/build-push-action@v5
  #       with:
  #         context: apps/web
  #         push: true
  #         platforms: linux/amd64,linux/arm64
  #         tags: ${{ steps.meta.outputs.tags }}
  #         labels: ${{ steps.meta.outputs.labels }}
  #         build-args: |
  #           VITE_COMMIT_SHA=${{ github.sha }}
  #     - name: Sign image
  #       run: |
  #         cosign sign --yes --key env://COSIGN_PRIVATE_KEY  ghcr.io/${{ github.repository }}:${{ github.sha }}
  #         cosign sign --yes --key env://COSIGN_PRIVATE_KEY  ghcr.io/${{ github.repository }}:latest
  #       env:
  #         COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
  #         COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
  # release-helm:
  #   runs-on: ubuntu-latest
  #   needs: [release-docker]
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Install Cosign
  #       uses: sigstore/cosign-installer@v3.5.0
  #     - name: Log in to GHCR
  #       uses: docker/login-action@v3
  #       with:
  #         registry: ghcr.io
  #         username: ${{ github.actor }}
  #         password: ${{ secrets.GITHUB_TOKEN }}
  #     - name: Package chart
  #       run: helm package production/helm/reviewer --version 0.0.${{ github.run_number }} --destination dist
  #     - name: Push chart
  #       run: helm push dist/*.tgz oci://ghcr.io/pvcnt/helm
  publish-cloudflare:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Download assets
        uses: actions/download-artifact@v4
        with:
          name: assets
          path: dist
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_TOKEN }}
          accountId: 1f74b8302712fd67d5eddea8c96eb776
          projectName: reviewer
          directory: dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}